#: import webbrowser webbrowser

<SettingsScreen>

    PBoxLayout:
        orientation: "vertical"
        pos_hint: {"top": 1}

        PToolbar:
            title: "Configuración"
            left_action_items: [["arrow-left", lambda x: root.manager.goto_previous_screen()]]

        ScrollView:

            PBoxLayout:
                orientation: "vertical"
                padding: dp(10)
                spacing: dp(10)
                adaptive_height: True

                ListItem:
                    text: "Cambia el fondo"
                    secondary_text: "Cambia el fondo entre claro y oscuro"
                    icon: root.theme_icon
                    on_release: root.change_theme()

                ListItem:
                    text: "Trailer DBH en Youtube"
                    secondary_text: "Disfruta!"
                    icon: "youtube"
                    on_release:
                        webbrowser.open("https://www.youtube.com/watch?v=euULGCe8Y50")

                ListItem:
                    text: "Info"
                    secondary_text: "Para saber más de esta app"
                    icon: "alert-circle"
                    on_release: root.open_about()

                Widget:
                    size_hint_y: None
                    height: dp(20)

                PLabel:
                    text: "Diseñado por [b]Lya[/b]"
                    font_name: "LexendMedium"
                    markup: True
                    adaptive_height: True


<AboutDialogContent>
    adaptive_height: True
    padding: dp(20)
    spacing: dp(10)
    orientation: "vertical"

    PLabel:
        text: "Info"
        font_size: dp(20)
        font_name: "LexendMedium"
        adaptive_height: True

    PLabel:
        text: "Chat con Connor es una aplicación de chat basada en character.ai."
        text_size: self.width, None
        halign: "center"
        adaptive_height: True
